config/routes.rb
Rails.application.routes.draw do
  get "import_details/index"
  get "sign_ups/new"
  get "sign_ups/create"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "affiliates", to: "affiliates#index"
  resources :merchants, only: [ :edit, :update, :index ]

  resources :imports, only: [ :create, :new, :index ] do
    get "details", to: "import_details#index", as: :import_details
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "imports#new"
  get "/sign_up", to: "sign_ups#new"
  post "/sign_up", to: "sign_ups#create"

  get "/sign_in", to: "sessions#new"
  post "/sign_in", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  root "sessions#new"
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def role_span(type)
    color = (type == "admin") ? "bg-info" : "bg-warning"
    class_style = "badge #{color} text-white ms-2 bg-gradient"
    label = type == "admin" ? "backdoor admin user" : "regular user"
    content_tag(:span, label, class: class_style)
  end
end

app/views/shared/navbar/_app_items.html.erb
<ul class="navbar-nav">
  <ul class="navbar-nav ms-auto d-flex flex-row align-items-center gap-3">
    <div class="d-flex flex-row gap-3 me-auto">
      <li class="nav-item">
        <%= link_to "Upload New Import", new_import_path, class: "nav-link fw-bold custom-hover #{active_nav_link(new_import_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Imports", imports_path, class: "nav-link fw-bold custom-hover #{active_nav_link(imports_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Affiliates", affiliates_path, class: "nav-link fw-bold custom-hover #{active_nav_link(affiliates_path)}" %>
      </li>
    </div>

    <li class="nav-item ms-5">
      <%= link_to "Logout", logout_path, method: :delete, class: "nav-link fw-bold text-danger custom-hover #{active_nav_link(logout_path)}" %>
    </li>
  </ul>
</ul>

app/views/shared/navbar/_current_user.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
    <span class="navbar-text">
      <%= turbo_frame_tag "merchant" do %>
        Welcome,&nbsp;
        <strong>
          <%= link_to current_user.slug, edit_merchant_path(current_user) %>
        </strong>
          <%= role_span(current_user.role) %>
      <% end %>
    </span>
  </li>
</ul>

app/views/shared/navbar/_items.html.erb
<ul class="navbar-nav ms-auto d-flex flex-row align-items-center gap-3">
  <% if logged_in? %>
    <div class="d-flex flex-row gap-3 me-auto">
      <li class="nav-item">
        <%= link_to "Upload New Import", new_import_path, class: "nav-link fw-bold custom-hover #{active_nav_link(new_import_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Imports", imports_path, class: "nav-link fw-bold custom-hover #{active_nav_link(imports_path)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Affiliates", affiliates_path, class: "nav-link fw-bold custom-hover #{active_nav_link(affiliates_path)}" %>
      </li>
    </div>

    <li class="nav-item ms-5">
      <%= link_to "Logout", logout_path, method: :delete, class: "nav-link fw-bold text-danger custom-hover #{active_nav_link(logout_path)}" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%= link_to "Sign up", sign_up_path, class: "nav-link fw-bold custom-hover #{active_nav_link(sign_up_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "Sign in", sign_in_path, class: "nav-link fw-bold custom-hover #{active_nav_link(sign_in_path)}" %>
    </li>
  <% end %>
</ul>

app/views/shared/navbar/_public_items.html.erb
<ul class="navbar-nav">
  <ul class="navbar-nav ms-auto d-flex flex-row align-items-center gap-3">
    <li class="nav-item">
      <%= link_to "Sign up", sign_up_path, class: "nav-link fw-bold custom-hover #{active_nav_link(sign_up_path)}" %>
    </li>
    <li class="nav-item">
      <%= link_to "Sign in", sign_in_path, class: "nav-link fw-bold custom-hover #{active_nav_link(sign_in_path)}" %>
    </li>
  </ul>
</ul>